### ISSUE TITLE
可以直接丢到vercel里部署吗

### ISSUE THREAD

**Issue by est7** [cunzaizhuyi/awesome-fe-sites#19]
很喜欢风格,但是技术栈不一致,想改下收录的网站丢vercel,没什么问题吧

**Comment by cunzaizhuyi** [comment]
你是说fork一个仓库，把里面的站点都改成安卓的站点，然后部署到vercel。也不会提pr到本仓库对吧。

如果是的话，可以的。

**Comment by cunzaizhuyi** [comment]
看你好像是做安卓的。不知道是不是这个意思。

**Comment by cunzaizhuyi** [comment]
不过vercel国内不太好访问，你可以继续netlify，设置个新的三级域名。比如androidsites.netlidy.app
